//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fbuCloset.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class uClosetSQLAdminEntities : DbContext
    {
        public uClosetSQLAdminEntities()
            : base("name=uClosetSQLAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AddfbUser_Result> AddfbUser(string fbID, string fbFirstname, string fbLastname, string fbUsername, string fbUser)
        {
            var fbIDParameter = fbID != null ?
                new ObjectParameter("fbID", fbID) :
                new ObjectParameter("fbID", typeof(string));
    
            var fbFirstnameParameter = fbFirstname != null ?
                new ObjectParameter("fbFirstname", fbFirstname) :
                new ObjectParameter("fbFirstname", typeof(string));
    
            var fbLastnameParameter = fbLastname != null ?
                new ObjectParameter("fbLastname", fbLastname) :
                new ObjectParameter("fbLastname", typeof(string));
    
            var fbUsernameParameter = fbUsername != null ?
                new ObjectParameter("fbUsername", fbUsername) :
                new ObjectParameter("fbUsername", typeof(string));
    
            var fbUserParameter = fbUser != null ?
                new ObjectParameter("fbUser", fbUser) :
                new ObjectParameter("fbUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddfbUser_Result>("AddfbUser", fbIDParameter, fbFirstnameParameter, fbLastnameParameter, fbUsernameParameter, fbUserParameter);
        }
    
        public virtual ObjectResult<AddSession_Result> AddSession(string asSessionID, string asUserID, string asUserName, Nullable<int> asPrivID, string asReqPage, string asAuthor)
        {
            var asSessionIDParameter = asSessionID != null ?
                new ObjectParameter("asSessionID", asSessionID) :
                new ObjectParameter("asSessionID", typeof(string));
    
            var asUserIDParameter = asUserID != null ?
                new ObjectParameter("asUserID", asUserID) :
                new ObjectParameter("asUserID", typeof(string));
    
            var asUserNameParameter = asUserName != null ?
                new ObjectParameter("asUserName", asUserName) :
                new ObjectParameter("asUserName", typeof(string));
    
            var asPrivIDParameter = asPrivID.HasValue ?
                new ObjectParameter("asPrivID", asPrivID) :
                new ObjectParameter("asPrivID", typeof(int));
    
            var asReqPageParameter = asReqPage != null ?
                new ObjectParameter("asReqPage", asReqPage) :
                new ObjectParameter("asReqPage", typeof(string));
    
            var asAuthorParameter = asAuthor != null ?
                new ObjectParameter("asAuthor", asAuthor) :
                new ObjectParameter("asAuthor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddSession_Result>("AddSession", asSessionIDParameter, asUserIDParameter, asUserNameParameter, asPrivIDParameter, asReqPageParameter, asAuthorParameter);
        }
    
        public virtual int ClearOutfitsandSharing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearOutfitsandSharing");
        }
    
        public virtual int ClearWardrobeandSharing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearWardrobeandSharing");
        }
    
        public virtual int CreateUser(string emailAddr, string username, string usrPASSWORD, string firstname, string lastname, string activateCode, Nullable<int> privID, string spUserID)
        {
            var emailAddrParameter = emailAddr != null ?
                new ObjectParameter("EmailAddr", emailAddr) :
                new ObjectParameter("EmailAddr", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var usrPASSWORDParameter = usrPASSWORD != null ?
                new ObjectParameter("usrPASSWORD", usrPASSWORD) :
                new ObjectParameter("usrPASSWORD", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("Firstname", firstname) :
                new ObjectParameter("Firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("Lastname", lastname) :
                new ObjectParameter("Lastname", typeof(string));
    
            var activateCodeParameter = activateCode != null ?
                new ObjectParameter("ActivateCode", activateCode) :
                new ObjectParameter("ActivateCode", typeof(string));
    
            var privIDParameter = privID.HasValue ?
                new ObjectParameter("privID", privID) :
                new ObjectParameter("privID", typeof(int));
    
            var spUserIDParameter = spUserID != null ?
                new ObjectParameter("spUserID", spUserID) :
                new ObjectParameter("spUserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUser", emailAddrParameter, usernameParameter, usrPASSWORDParameter, firstnameParameter, lastnameParameter, activateCodeParameter, privIDParameter, spUserIDParameter);
        }
    
        public virtual int Login(string myEmailAddr, string myPASSWORD, string mySessionID)
        {
            var myEmailAddrParameter = myEmailAddr != null ?
                new ObjectParameter("myEmailAddr", myEmailAddr) :
                new ObjectParameter("myEmailAddr", typeof(string));
    
            var myPASSWORDParameter = myPASSWORD != null ?
                new ObjectParameter("myPASSWORD", myPASSWORD) :
                new ObjectParameter("myPASSWORD", typeof(string));
    
            var mySessionIDParameter = mySessionID != null ?
                new ObjectParameter("mySessionID", mySessionID) :
                new ObjectParameter("mySessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Login", myEmailAddrParameter, myPASSWORDParameter, mySessionIDParameter);
        }
    
        public virtual ObjectResult<spAdd_CustomCategories_Result> spAdd_CustomCategories(Nullable<bool> fgShow, string customDesc, Nullable<decimal> customParentID, string userID)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var customDescParameter = customDesc != null ?
                new ObjectParameter("CustomDesc", customDesc) :
                new ObjectParameter("CustomDesc", typeof(string));
    
            var customParentIDParameter = customParentID.HasValue ?
                new ObjectParameter("CustomParentID", customParentID) :
                new ObjectParameter("CustomParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAdd_CustomCategories_Result>("spAdd_CustomCategories", fgShowParameter, customDescParameter, customParentIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spAdd_CustomOutfitCategories_Result> spAdd_CustomOutfitCategories(Nullable<bool> fgShow, string customDesc, Nullable<decimal> customParentID, string userID)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var customDescParameter = customDesc != null ?
                new ObjectParameter("CustomDesc", customDesc) :
                new ObjectParameter("CustomDesc", typeof(string));
    
            var customParentIDParameter = customParentID.HasValue ?
                new ObjectParameter("CustomParentID", customParentID) :
                new ObjectParameter("CustomParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAdd_CustomOutfitCategories_Result>("spAdd_CustomOutfitCategories", fgShowParameter, customDescParameter, customParentIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spAdd_File_Result> spAdd_File(string userID, Nullable<int> clothingTypeID, string docDesc, string fileName, string docType, Nullable<decimal> size, string name, string web, string designer, string productName)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var clothingTypeIDParameter = clothingTypeID.HasValue ?
                new ObjectParameter("ClothingTypeID", clothingTypeID) :
                new ObjectParameter("ClothingTypeID", typeof(int));
    
            var docDescParameter = docDesc != null ?
                new ObjectParameter("DocDesc", docDesc) :
                new ObjectParameter("DocDesc", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var docTypeParameter = docType != null ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(string));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(decimal));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var webParameter = web != null ?
                new ObjectParameter("Web", web) :
                new ObjectParameter("Web", typeof(string));
    
            var designerParameter = designer != null ?
                new ObjectParameter("Designer", designer) :
                new ObjectParameter("Designer", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAdd_File_Result>("spAdd_File", userIDParameter, clothingTypeIDParameter, docDescParameter, fileNameParameter, docTypeParameter, sizeParameter, nameParameter, webParameter, designerParameter, productNameParameter);
        }
    
        public virtual ObjectResult<spAdd_OutfitImage_Result> spAdd_OutfitImage(string userID, string outfitID, string filename)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            var filenameParameter = filename != null ?
                new ObjectParameter("Filename", filename) :
                new ObjectParameter("Filename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAdd_OutfitImage_Result>("spAdd_OutfitImage", userIDParameter, outfitIDParameter, filenameParameter);
        }
    
        public virtual ObjectResult<spAdd_UserOutfit_OBJ_Result> spAdd_UserOutfit_OBJ(string userID, Nullable<int> outfitGroupID, string attachID, Nullable<int> frameID, string userOutfitDesc, Nullable<bool> sessionFG, string createUser, string userOutfitID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitGroupIDParameter = outfitGroupID.HasValue ?
                new ObjectParameter("OutfitGroupID", outfitGroupID) :
                new ObjectParameter("OutfitGroupID", typeof(int));
    
            var attachIDParameter = attachID != null ?
                new ObjectParameter("AttachID", attachID) :
                new ObjectParameter("AttachID", typeof(string));
    
            var frameIDParameter = frameID.HasValue ?
                new ObjectParameter("FrameID", frameID) :
                new ObjectParameter("FrameID", typeof(int));
    
            var userOutfitDescParameter = userOutfitDesc != null ?
                new ObjectParameter("UserOutfitDesc", userOutfitDesc) :
                new ObjectParameter("UserOutfitDesc", typeof(string));
    
            var sessionFGParameter = sessionFG.HasValue ?
                new ObjectParameter("SessionFG", sessionFG) :
                new ObjectParameter("SessionFG", typeof(bool));
    
            var createUserParameter = createUser != null ?
                new ObjectParameter("CreateUser", createUser) :
                new ObjectParameter("CreateUser", typeof(string));
    
            var userOutfitIDParameter = userOutfitID != null ?
                new ObjectParameter("UserOutfitID", userOutfitID) :
                new ObjectParameter("UserOutfitID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAdd_UserOutfit_OBJ_Result>("spAdd_UserOutfit_OBJ", userIDParameter, outfitGroupIDParameter, attachIDParameter, frameIDParameter, userOutfitDescParameter, sessionFGParameter, createUserParameter, userOutfitIDParameter);
        }
    
        public virtual ObjectResult<spAddShareFriends_Result> spAddShareFriends(string attachmentID, string friendID)
        {
            var attachmentIDParameter = attachmentID != null ?
                new ObjectParameter("AttachmentID", attachmentID) :
                new ObjectParameter("AttachmentID", typeof(string));
    
            var friendIDParameter = friendID != null ?
                new ObjectParameter("FriendID", friendID) :
                new ObjectParameter("FriendID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAddShareFriends_Result>("spAddShareFriends", attachmentIDParameter, friendIDParameter);
        }
    
        public virtual ObjectResult<spAddShareOutfitFriends_Result> spAddShareOutfitFriends(string outfitID, string friendID)
        {
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            var friendIDParameter = friendID != null ?
                new ObjectParameter("FriendID", friendID) :
                new ObjectParameter("FriendID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAddShareOutfitFriends_Result>("spAddShareOutfitFriends", outfitIDParameter, friendIDParameter);
        }
    
        public virtual ObjectResult<string> spCheck_Dup(string userID, Nullable<int> clothingTypeID, string sourceName, string designer, string productName, string name, Nullable<int> dupCHKType)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var clothingTypeIDParameter = clothingTypeID.HasValue ?
                new ObjectParameter("ClothingTypeID", clothingTypeID) :
                new ObjectParameter("ClothingTypeID", typeof(int));
    
            var sourceNameParameter = sourceName != null ?
                new ObjectParameter("SourceName", sourceName) :
                new ObjectParameter("SourceName", typeof(string));
    
            var designerParameter = designer != null ?
                new ObjectParameter("Designer", designer) :
                new ObjectParameter("Designer", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var dupCHKTypeParameter = dupCHKType.HasValue ?
                new ObjectParameter("DupCHKType", dupCHKType) :
                new ObjectParameter("DupCHKType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCheck_Dup", userIDParameter, clothingTypeIDParameter, sourceNameParameter, designerParameter, productNameParameter, nameParameter, dupCHKTypeParameter);
        }
    
        public virtual int spChildren(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChildren", idParameter);
        }
    
        public virtual ObjectResult<spClearShareFriends_Result> spClearShareFriends(string attachmentID)
        {
            var attachmentIDParameter = attachmentID != null ?
                new ObjectParameter("AttachmentID", attachmentID) :
                new ObjectParameter("AttachmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spClearShareFriends_Result>("spClearShareFriends", attachmentIDParameter);
        }
    
        public virtual ObjectResult<spClearShareOutfitFriends_Result> spClearShareOutfitFriends(string outfitID)
        {
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spClearShareOutfitFriends_Result>("spClearShareOutfitFriends", outfitIDParameter);
        }
    
        public virtual ObjectResult<spDeleteHideOufit_Result> spDeleteHideOufit(string dhoUserID, string dhoOutfitID)
        {
            var dhoUserIDParameter = dhoUserID != null ?
                new ObjectParameter("dhoUserID", dhoUserID) :
                new ObjectParameter("dhoUserID", typeof(string));
    
            var dhoOutfitIDParameter = dhoOutfitID != null ?
                new ObjectParameter("dhoOutfitID", dhoOutfitID) :
                new ObjectParameter("dhoOutfitID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDeleteHideOufit_Result>("spDeleteHideOufit", dhoUserIDParameter, dhoOutfitIDParameter);
        }
    
        public virtual ObjectResult<spDeleteHideWardrobeImage_Result> spDeleteHideWardrobeImage(string dhwiUserID, string dhwiImageID)
        {
            var dhwiUserIDParameter = dhwiUserID != null ?
                new ObjectParameter("dhwiUserID", dhwiUserID) :
                new ObjectParameter("dhwiUserID", typeof(string));
    
            var dhwiImageIDParameter = dhwiImageID != null ?
                new ObjectParameter("dhwiImageID", dhwiImageID) :
                new ObjectParameter("dhwiImageID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDeleteHideWardrobeImage_Result>("spDeleteHideWardrobeImage", dhwiUserIDParameter, dhwiImageIDParameter);
        }
    
        public virtual ObjectResult<spGet_File_Result> spGet_File(string fileID)
        {
            var fileIDParameter = fileID != null ?
                new ObjectParameter("FileID", fileID) :
                new ObjectParameter("FileID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_File_Result>("spGet_File", fileIDParameter);
        }
    
        public virtual ObjectResult<spGet_FileList_Result> spGet_FileList(string ownerUserID, string userID, Nullable<int> clothingTypeID, string sessionID, Nullable<int> vendorTypeID, Nullable<bool> show)
        {
            var ownerUserIDParameter = ownerUserID != null ?
                new ObjectParameter("OwnerUserID", ownerUserID) :
                new ObjectParameter("OwnerUserID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var clothingTypeIDParameter = clothingTypeID.HasValue ?
                new ObjectParameter("ClothingTypeID", clothingTypeID) :
                new ObjectParameter("ClothingTypeID", typeof(int));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var vendorTypeIDParameter = vendorTypeID.HasValue ?
                new ObjectParameter("VendorTypeID", vendorTypeID) :
                new ObjectParameter("VendorTypeID", typeof(int));
    
            var showParameter = show.HasValue ?
                new ObjectParameter("Show", show) :
                new ObjectParameter("Show", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_FileList_Result>("spGet_FileList", ownerUserIDParameter, userIDParameter, clothingTypeIDParameter, sessionIDParameter, vendorTypeIDParameter, showParameter);
        }
    
        public virtual ObjectResult<spGet_MerchantList_Result> spGet_MerchantList(string merchantInit)
        {
            var merchantInitParameter = merchantInit != null ?
                new ObjectParameter("MerchantInit", merchantInit) :
                new ObjectParameter("MerchantInit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_MerchantList_Result>("spGet_MerchantList", merchantInitParameter);
        }
    
        public virtual ObjectResult<spGet_UserGarmentAttachmentList_Result> spGet_UserGarmentAttachmentList(string sessionID, string userID, Nullable<int> clothingtypeID)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var clothingtypeIDParameter = clothingtypeID.HasValue ?
                new ObjectParameter("ClothingtypeID", clothingtypeID) :
                new ObjectParameter("ClothingtypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_UserGarmentAttachmentList_Result>("spGet_UserGarmentAttachmentList", sessionIDParameter, userIDParameter, clothingtypeIDParameter);
        }
    
        public virtual ObjectResult<spGetAttachment_Result> spGetAttachment(string attachmentID)
        {
            var attachmentIDParameter = attachmentID != null ?
                new ObjectParameter("AttachmentID", attachmentID) :
                new ObjectParameter("AttachmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAttachment_Result>("spGetAttachment", attachmentIDParameter);
        }
    
        public virtual ObjectResult<string> spGetFBUser(string fBUserID)
        {
            var fBUserIDParameter = fBUserID != null ?
                new ObjectParameter("FBUserID", fBUserID) :
                new ObjectParameter("FBUserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetFBUser", fBUserIDParameter);
        }
    
        public virtual ObjectResult<spGetFBUserList_Result> spGetFBUserList(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFBUserList_Result>("spGetFBUserList", userIDParameter);
        }
    
        public virtual ObjectResult<spGetFBUserOutfitList_Result> spGetFBUserOutfitList(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFBUserOutfitList_Result>("spGetFBUserOutfitList", userIDParameter);
        }
    
        public virtual ObjectResult<spGetOutfitUsedMenuItems_Result> spGetOutfitUsedMenuItems(Nullable<bool> fgShow, Nullable<decimal> outfitGroupParentID, string userID, string closetUserID, string sessionID, string userType)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var outfitGroupParentIDParameter = outfitGroupParentID.HasValue ?
                new ObjectParameter("OutfitGroupParentID", outfitGroupParentID) :
                new ObjectParameter("OutfitGroupParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var closetUserIDParameter = closetUserID != null ?
                new ObjectParameter("ClosetUserID", closetUserID) :
                new ObjectParameter("ClosetUserID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetOutfitUsedMenuItems_Result>("spGetOutfitUsedMenuItems", fgShowParameter, outfitGroupParentIDParameter, userIDParameter, closetUserIDParameter, sessionIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spGetShareFriends_Result> spGetShareFriends(string attachmentID)
        {
            var attachmentIDParameter = attachmentID != null ?
                new ObjectParameter("AttachmentID", attachmentID) :
                new ObjectParameter("AttachmentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetShareFriends_Result>("spGetShareFriends", attachmentIDParameter);
        }
    
        public virtual ObjectResult<spGetShareOutfitFriends_Result> spGetShareOutfitFriends(string outfitID)
        {
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetShareOutfitFriends_Result>("spGetShareOutfitFriends", outfitIDParameter);
        }
    
        public virtual ObjectResult<spGetUsersUsedMenuItems_Result> spGetUsersUsedMenuItems(Nullable<bool> fgShow, Nullable<decimal> clothParentID, string userID, string closetUserID, string sessionID, string userType)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var clothParentIDParameter = clothParentID.HasValue ?
                new ObjectParameter("ClothParentID", clothParentID) :
                new ObjectParameter("ClothParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var closetUserIDParameter = closetUserID != null ?
                new ObjectParameter("ClosetUserID", closetUserID) :
                new ObjectParameter("ClosetUserID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUsersUsedMenuItems_Result>("spGetUsersUsedMenuItems", fgShowParameter, clothParentIDParameter, userIDParameter, closetUserIDParameter, sessionIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spSave_Outfit_Result> spSave_Outfit(string userID, string outfitID, string outfitDesc, Nullable<int> outfitCategoryID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            var outfitDescParameter = outfitDesc != null ?
                new ObjectParameter("OutfitDesc", outfitDesc) :
                new ObjectParameter("OutfitDesc", typeof(string));
    
            var outfitCategoryIDParameter = outfitCategoryID.HasValue ?
                new ObjectParameter("OutfitCategoryID", outfitCategoryID) :
                new ObjectParameter("OutfitCategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSave_Outfit_Result>("spSave_Outfit", userIDParameter, outfitIDParameter, outfitDescParameter, outfitCategoryIDParameter);
        }
    
        public virtual ObjectResult<spUserType_Result> spUserType(string utUserID)
        {
            var utUserIDParameter = utUserID != null ?
                new ObjectParameter("utUserID", utUserID) :
                new ObjectParameter("utUserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserType_Result>("spUserType", utUserIDParameter);
        }
    
        public virtual ObjectResult<spView_ClothingCategories_Result> spView_ClothingCategories(Nullable<bool> fgShow, Nullable<decimal> clothParentID)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var clothParentIDParameter = clothParentID.HasValue ?
                new ObjectParameter("ClothParentID", clothParentID) :
                new ObjectParameter("ClothParentID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_ClothingCategories_Result>("spView_ClothingCategories", fgShowParameter, clothParentIDParameter);
        }
    
        public virtual ObjectResult<spView_ClothingParentCategories_Result> spView_ClothingParentCategories(Nullable<bool> fgShow, Nullable<decimal> clothParentID, string userID, string sessionID, string userType)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var clothParentIDParameter = clothParentID.HasValue ?
                new ObjectParameter("ClothParentID", clothParentID) :
                new ObjectParameter("ClothParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_ClothingParentCategories_Result>("spView_ClothingParentCategories", fgShowParameter, clothParentIDParameter, userIDParameter, sessionIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spView_CustomCategories_Result> spView_CustomCategories(Nullable<bool> fgShow, Nullable<decimal> customParentID, string userID)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var customParentIDParameter = customParentID.HasValue ?
                new ObjectParameter("CustomParentID", customParentID) :
                new ObjectParameter("CustomParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_CustomCategories_Result>("spView_CustomCategories", fgShowParameter, customParentIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spView_FeaturedOutfit_Result> spView_FeaturedOutfit(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_FeaturedOutfit_Result>("spView_FeaturedOutfit", userIDParameter);
        }
    
        public virtual ObjectResult<spView_FeatureOutfit_Result> spView_FeatureOutfit(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_FeatureOutfit_Result>("spView_FeatureOutfit", userIDParameter);
        }
    
        public virtual ObjectResult<spView_OutfitGroup_Result> spView_OutfitGroup(Nullable<bool> fgShow, Nullable<decimal> outfitGroupParentID)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var outfitGroupParentIDParameter = outfitGroupParentID.HasValue ?
                new ObjectParameter("OutfitGroupParentID", outfitGroupParentID) :
                new ObjectParameter("OutfitGroupParentID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_OutfitGroup_Result>("spView_OutfitGroup", fgShowParameter, outfitGroupParentIDParameter);
        }
    
        public virtual ObjectResult<spView_OutfitGroupParentCategories_Result> spView_OutfitGroupParentCategories(Nullable<bool> fgShow, Nullable<decimal> outfitGroupParentID, string userID, string sessionID, string userType)
        {
            var fgShowParameter = fgShow.HasValue ?
                new ObjectParameter("fgShow", fgShow) :
                new ObjectParameter("fgShow", typeof(bool));
    
            var outfitGroupParentIDParameter = outfitGroupParentID.HasValue ?
                new ObjectParameter("OutfitGroupParentID", outfitGroupParentID) :
                new ObjectParameter("OutfitGroupParentID", typeof(decimal));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_OutfitGroupParentCategories_Result>("spView_OutfitGroupParentCategories", fgShowParameter, outfitGroupParentIDParameter, userIDParameter, sessionIDParameter, userTypeParameter);
        }
    
        public virtual ObjectResult<spView_UserOutfit_Result> spView_UserOutfit(string userID, string outfitID, string sessionID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_UserOutfit_Result>("spView_UserOutfit", userIDParameter, outfitIDParameter, sessionIDParameter);
        }
    
        public virtual ObjectResult<spView_UserOutfits_Result> spView_UserOutfits(string userID, string outfitID, string sessionID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitIDParameter = outfitID != null ?
                new ObjectParameter("OutfitID", outfitID) :
                new ObjectParameter("OutfitID", typeof(string));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_UserOutfits_Result>("spView_UserOutfits", userIDParameter, outfitIDParameter, sessionIDParameter);
        }
    
        public virtual ObjectResult<spView_UserOutfitsDesc_Result> spView_UserOutfitsDesc(string userID, Nullable<int> outfitGroupID, string sessionID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var outfitGroupIDParameter = outfitGroupID.HasValue ?
                new ObjectParameter("OutfitGroupID", outfitGroupID) :
                new ObjectParameter("OutfitGroupID", typeof(int));
    
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spView_UserOutfitsDesc_Result>("spView_UserOutfitsDesc", userIDParameter, outfitGroupIDParameter, sessionIDParameter);
        }
    }
}
